# Esempio di estensione config (da fondere con il vostro config.yaml)
data_sources:
  preferred: "oanda"   # o: yahoo, dukascopy_csv
  yahoo:
    symbol: "EURUSD=X"
    interval: "1h"
    start: "2021-01-01"
    end: null
  oanda:
    instrument: "EUR_USD"
    granularity: "H1"
    from: "2021-01-01T00:00:00Z"
    to: null
    price: "M"
    batch: 5000
  dukascopy_csv:
    path: "data/EURUSD_H1_dukascopy.csv"
    tz: "UTC"

execution:
  broker: "oanda"   # o: paper
  oanda:
    account_type: "practice"   # practice | live
    account_id: "YOUR_ACCOUNT_ID"
    api_key: "YOUR_API_KEY"
    api_url_practice: "https://api-fxpractice.oanda.com/v3"
    api_url_live: "https://api-fxtrade.oanda.com/v3"
  paper:
    starting_cash: 10000.0

monitoring:
  telegram:
    enabled: false
    bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
    chat_id: "YOUR_CHAT_ID"
  heartbeat:
    enabled: true
    file: "results/heartbeat.txt"
    interval_seconds: 60

# Esempio aggiunta strategia mean reversion
strategies:
  MR_RSI:
    type: "mean_reversion_adx_rsi"
    params: { rsi_period: 14, rsi_low: 30, rsi_high: 70, adx_period: 14, adx_threshold: 20 }


risk:
  max_currency_exposure: 0.3

execution:
  mode: dynamic
  allowed_hours: [7,20]

# Controlli operativi aggiuntivi
trading_hours:
  - start: "07:00"
    end: "22:00"
    weekdays: [1,2,3,4,5]
max_currency_exposure:
  EUR: 2
  USD: 2
  JPY: 2
execution:
  mode: dynamic
  spread_base: 0.00010
  slippage_base: 0.00005
  session_multipliers:
    Asia: 1.4
    London: 1.0
    NewYork: 1.2
    Off: 1.8
